sudo: false
language: python
matrix:
  include:
  - python: 2.7

before_install:
- openssl aes-256-cbc -K $encrypted_4d8c1e02c0d1_key -iv $encrypted_4d8c1e02c0d1_iv
  -in SimpleRest-2ebb665be95e.json.enc -out SimpleRest-2ebb665be95e.json -d

install:
- pip install -r requirements.txt
script:
- python test_app.py
cache:
- pip


deploy:
  - provider: gae
    keyfile: SimpleRest-2ebb665be95e.json.enc
    project: SimpleRest
    on: master

  - provider: heroku
      api_key:
        secure: hICDlamg2gqiIgwLMpaO1H+Q+oTxGb+t++q6rxi4VcbvyBLXMb2urO+NMbzEbMAhqEiKLW9Ug15FNO32NIr6iF8gSoQz+MjKAT836EePhRfePZEzkryDnSqya9aFJPe6Erd8/i09ZjIhTr3I/agsM0k4TpKsxQgYke/ojJZ96YtGlerLSd9T0z9kin+Ia8nsiXG3P4kxr2La4wP8zD12+VsLM1C3cxgZ5naHf3IuEjYbBU2gLEesPAaO+7ku1bf7wosI0EQf+mQH3QsawlsI2RX7bJObHw9bRjYaYeanpPl+/GalPDrigNFdfFP7EgL//hD7cIW3a3tPOqdbyD1fOUAhEJuJNuxEgvz5sF50N+xDGPKCeFS0OFhSTLtuYDGyIkF+esOdAzY/dlY3Gj4ZsAS5MTUXDVgrTTDWivsrIAFcdVQWdZ0kKfe7xvhCygNOzRQS3bA6kKXk24ToBHtA4EfBy9KLEus2OHza3V+MBVLxHnTP07Ar/DbDRz8Vtg0Cn1JKz1ja7TR37WUdl1WJ/6z6iv9sY2/5GJYlWe0Rm+fMxh8NBIQZtluLFdlPRESASAy8BvkVhcsWRi1iUKyUpwEOAgkcuQgBktVtvyfqiRRy3ZbEWR4xfV9RYicwqpA9E5s7TWSduCGHdxVQIklYe+L9juBgvQ52nXXkcW4MNKI=
      app: devsu-tst
      on: master
