version: '2.1'
services:
  app1:
    container_name: app1
    build:
      context:  ./app1
      dockerfile: Dockerfile
    expose:
      - "5000"
    ports:
      - '5000:5000'

  app2:
    container_name: app2
    build:
      context:  ./app1
      dockerfile: Dockerfile
    expose:
        - "5000"
    ports:
      - '5001:5000'

  proxy:
    container_name: nginx
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
