# Version 0.0.1
FROM fedora
MAINTAINER Antonio Insuasti "antonio@insuasti.ec"
RUN ln -s /bin/python3 /bin/python
RUN git clone https://github.com/Wolfant/DShello.git
RUN cd DShello
RUN pyton 
EXPOSE 5000
